package com.mogan.portfolio.controller;
import com.mogan.portfolio.model.*;import com.mogan.portfolio.repo.*;import jakarta.servlet.http.*;import jakarta.validation.constraints.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/public") public class PublicController{
final ProjectRepository pr;final ProjectLikeRepository lr;final PortfolioItemRepository ir;final ContactMessageRepository mr;final SiteSettingRepository sr;PublicController(ProjectRepository p,ProjectLikeRepository l,PortfolioItemRepository i,ContactMessageRepository m,SiteSettingRepository s){pr=p;lr=l;ir=i;mr=m;sr=s;}
Map<String,Object> project(Project p,HttpServletRequest req){Map<String,Object>m=new LinkedHashMap<>();m.put("id",p.id);m.put("slug",p.slug);m.put("title",p.title);m.put("category",p.category);m.put("type",p.type);m.put("description",p.description);m.put("technologies",p.technologies==null?List.of():Arrays.asList(p.technologies.split("\\|")));m.put("imagePath",p.imagePath);m.put("githubUrl",p.githubUrl);m.put("liveUrl",p.liveUrl);m.put("featured",p.featured);m.put("likes",lr.countByProject(p));m.put("views",p.views);return m;}
@GetMapping("/projects") List<Map<String,Object>> projects(HttpServletRequest r){return pr.findByPublishedTrueOrderByFeaturedDescIdAsc().stream().map(p->project(p,r)).toList();}
@GetMapping("/projects/{slug}") ResponseEntity<?> one(@PathVariable String slug,HttpServletRequest r){return pr.findBySlug(slug).map(p->ResponseEntity.ok(project(p,r))).orElseGet(()->ResponseEntity.notFound().build());}
@PostMapping("/projects/{slug}/view") ResponseEntity<?> view(@PathVariable String slug){var p=pr.findBySlug(slug);if(p.isEmpty())return ResponseEntity.notFound().build();p.get().views++;pr.save(p.get());return ResponseEntity.ok(Map.of("views",p.get().views));}
@PostMapping("/projects/{slug}/like") ResponseEntity<?> like(@PathVariable String slug,HttpServletRequest req,HttpServletResponse res){var p=pr.findBySlug(slug);if(p.isEmpty())return ResponseEntity.notFound().build();String visitor=req.getCookies()==null?null:Arrays.stream(req.getCookies()).filter(c->"visitor_id".equals(c.getName())).map(Cookie::getValue).findFirst().orElse(null);if(visitor==null){visitor=UUID.randomUUID().toString();Cookie c=new Cookie("visitor_id",visitor);c.setPath("/");c.setMaxAge(31536000);c.setHttpOnly(true);res.addCookie(c);}var existing=lr.findByProjectAndVisitorId(p.get(),visitor);boolean liked;if(existing.isPresent()){lr.delete(existing.get());liked=false;}else{ProjectLike x=new ProjectLike();x.project=p.get();x.visitorId=visitor;lr.save(x);liked=true;}return ResponseEntity.ok(Map.of("liked",liked,"likes",lr.countByProject(p.get())));}
@GetMapping("/content") List<PortfolioItem> content(){return ir.findByPublishedTrueOrderByTypeAscSortOrderAsc();}
@GetMapping("/settings") Map<String,String> settings(){Map<String,String>m=new LinkedHashMap<>();sr.findAll().forEach(x->m.put(x.settingKey,x.settingValue));return m;}
record Contact(@NotBlank String name,@Email @NotBlank String email,String subject,@NotBlank String message){}
@PostMapping("/contact") ResponseEntity<?> contact(@RequestBody Contact c){ContactMessage x=new ContactMessage();x.name=c.name();x.email=c.email();x.subject=c.subject();x.message=c.message();mr.save(x);return ResponseEntity.ok(Map.of("success",true));}
@GetMapping("/assistant") Map<String,String> assistant(@RequestParam String question){String q=question.toLowerCase(Locale.ROOT);List<Project> ps=pr.findByPublishedTrueOrderByFeaturedDescIdAsc();List<PortfolioItem> items=ir.findByPublishedTrueOrderByTypeAscSortOrderAsc();String answer;
if(q.matches(".*(project|projects|built|work).*")&&!q.contains("skill")){answer="Current projects include: "+ps.stream().map(x->x.title).limit(8).reduce((a,b)->a+", "+b).orElse("the projects listed on the portfolio")+".";}else if(q.matches(".*(skill|technology|technologies|language).*")){answer=items.stream().filter(x->"SKILL".equalsIgnoreCase(x.type)).map(x->x.title+" — "+x.description).limit(10).reduce((a,b)->a+"; "+b).orElse("Skills are available in the Skills section.");}else if(q.matches(".*(education|degree|study|college|university).*")){answer=items.stream().filter(x->"EDUCATION".equalsIgnoreCase(x.type)).map(x->x.title+": "+x.description).reduce((a,b)->a+" "+b).orElse("Education details are available in the Education section.");}else if(q.matches(".*(experience|intern|job|work experience).*")){answer=items.stream().filter(x->"EXPERIENCE".equalsIgnoreCase(x.type)).map(x->x.title+": "+x.description).reduce((a,b)->a+" "+b).orElse("Experience details are available in the Experience section.");}else if(q.matches(".*(certificate|certification|credential).*")){answer=items.stream().filter(x->"CERTIFICATION".equalsIgnoreCase(x.type)).map(x->x.title).reduce((a,b)->a+", "+b).orElse("Certification details are available in the Certificates section.");}else if(q.matches(".*(contact|email|reach|hire).*")){String e=sr.findById("email").map(x->x.settingValue).orElse("");answer=e.isBlank()?"Please use the Contact page to get in touch.":"You can contact Moganavel at "+e+".";}else{answer="I’m the built-in portfolio assistant. Ask me about projects, skills, education, experience, certifications, or contact information.";}return Map.of("answer",answer);}
}
